[project]
name = "fab"
version = "0.1.0"
description = "Fast Assembler for Bootc."
authors = [
    {name = "Costin Gament"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "configargparse (>=1.7,<2.0)",
    "pyyaml (>=6.0.2,<7.0.0)"
]
[project.scripts]
fab = "fab.cli:FabCli"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

